{{- $chartName := include "job-manager.name" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $tracingUrl := include "job-manager.tracingUrl" . -}}
{{- $metricsUrl := include "job-manager.metricsUrl" . -}}
{{- $db := (include "common.db.merged" .) | fromYaml }}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  DB_HOST: {{ $db.host | quote }}
  DB_PORT: {{ $db.port | quote}}
  DB_NAME: {{ $db.name | quote }}
  DB_SCHEMA: {{ $db.schema | quote }}
  DB_LOGGING: {{ $db.logging | quote }}
  DB_SSL_ENABLE: {{ $db.sslEnabled | quote }}
  PGAPPNAME: {{ $chartName }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
  HEARTBEAT_ENABLED: {{ .Values.env.heartbeat.enabled | quote }}
  HEARTBEAT_FAILED_DURATION_MS: {{ .Values.env.heartbeat.failedDurationMs | quote }}
  HEARTBEAT_SERVICE_URL: {{ .Values.serviceUrls.heartbeatManager | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  TELEMETRY_TRACING_RATIO: {{ .Values.env.tracing.ratio | quote }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
{{- end }}
